name: Test and Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Build project
      run: npm run build
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: dist/  # Thay đổi nếu thư mục build khác

  deploy:
    needs: test  # Chỉ chạy sau khi job test thành công
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: build-output
        path: dist/
    
    - name: Setup Pages
      uses: actions/configure-pages@v3
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: 'dist/'
        
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
